# -*- coding: utf-8 -*-
"""Assignment04_solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1AjykPNk7spe29ThjzTJX9wSnDEEJlK

# CSE 101: Assignment 4

## Problem 1
Write a function `normalize_username(name)` that:
1) Strips leading/trailing spaces
2) Converts to lowercase
3) Replaces **all spaces** inside with underscores `_`
4) Returns the result

Example: `'  John Adam  '` → `'John Adam'`
"""

def normalize_username(name):
    name = name.strip()
    name = name.lower()
    name = name.replace(" ","_")
    return name

# Try:
print(normalize_username("  John Adam  "))

"""## Problem 2 — Count a Substring (Overlapping allowed)
Write a function `count_substring(text, sub)` that counts how many times `sub` appears in `text`, **including overlapping matches**.

Example: `count_substring('banana', 'ana')` should be `2` (positions 1 and 3).
"""

def count_substring(text, sub):
  count = 0
  i = 0

  while i < len(text):
    if text.startswith(sub,i):
      count = count + 1
    i = i + 1
  return count

# Try:
print(count_substring("banana", "ana"))  # 2

"""## Problem 3 — Title-Case Without `.title()`
Write a function `simple_title_case(sentence)` that:
- Strips extra spaces at the ends
- Splits words by spaces (assume single spaces between words after stripping)
- Capitalizes the first letter of each word and makes the rest lowercase
- Returns the new sentence

Example: `'hELLo wORLd'` → `'Hello World'`
"""

def simple_title_case(sentence):
    words = sentence.split()
    result = []

    for word in words:
      result.append(word.capitalize())
    return " ".join(result)

# Try:
print(simple_title_case("hELLo wORLd"))

"""## Problem 4 — Mask Digits
Write a function `mask_digits(s)` that replaces every digit (`0`–`9`) with `*` and returns the result.

Example: `'Room 12B, Floor 7'` → `'Room **B, Floor *'`
"""

def mask_digits(s):
  result = ""

  for char in s:
    if char.isdigit():
      result = result + "*"
    else:
      result = result + char
  return result
# Try:
print(mask_digits("Room 12B, Floor 7"))

"""## Problem 5 — Replace Only the First Occurrence
Write a function `replace_first(text, old, new)` that replaces **only the first** occurrence of `old` with `new`.
If `old` is not found, return the original text.

Example: `replace_first('one one one', 'one', '1')` → `'1 one one'`
"""

def replace_first(text, old, new):
   return text.replace(old, new, 1)


print(replace_first("one one one", "one", "1"))

"""## Problem 6 — Parse and Sum Integers from a Mixed String
Write a function `sum_numbers_in_text(text)` that finds all **positive integers** embedded in `text` and returns their sum.

Rules:
- Numbers are sequences of digits.
- Use only string operations/loops.

Example: `'I ran 12 km and then 3 km'` → `15`
"""

def sum_numbers_in_text(text):
    words = text.split()
    total = 0

    for word in words:
      if word.isdigit():
        total = total + int(word)
    return total



# Try:
print(sum_numbers_in_text("I ran 12 km and then 3 km"))  # 15

"""# Files

Run this cell to create it locally `sample_mbox.txt`
"""

sample_text = '''From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Date: Sat, 5 Jan 2008 09:12:18 -0500
To: source@collab.sakaiproject.org
From: stephen.marquard@uct.ac.za
Subject: [sakai] svn commit: r39772 - content/branches/

From: louis@media.berkeley.edu Fri Jan  4 18:10:48 2008
Subject: Re: Meeting update!
Hi team,
The meeting is at 3pm.

From: zqian@umich.edu Fri Jan  4 16:05:12 2008
Subject: Quiz-3 marks (updated).
Please check the spreadsheet.

From: rjlowe@iupui.edu Fri Jan  4 07:02:32 2008
Subject: Lunch?
Are we free at 1:00pm?

This line has trailing spaces.

From: david.horwitz@uct.ac.za Thu Jan  3 11:22:33 2008
Subject: Re: Lunch?
Sure—let's go.

Random notes:
- Python, files, and errors.
- Email: test.user@Example.COM

Subject: This is a subject without a From line
'''
with open("sample_mbox.txt", "w", encoding="utf-8") as f:
    f.write(sample_text)

print("Created sample_mbox.txt")

"""## Problem 7: Smart Subject Counter

Write a program that:
1) Prompts for a filename
2) Uses `try/except` to handle missing files
3) Reads the file line by line
4) Prints lines that start with `'Subject:'`
5) Counts:
   - total lines in file
   - total subject lines
6) Prints the percentage of lines that are subject lines

**Output should include** total lines, subject lines, and percent.
"""

# Write your solution here

filename = input("Enter file name: ")

try:
    fl = open(filename)
except:
    print("File can't found")
    exit()

total_lines = 0
subject_lines = 0

for line in fl:
    total_lines = total_lines + 1

    if line.startswith("Subject:"):
        subject_lines =  subject_lines + 1

percent = (subject_lines / total_lines) * 100

print("Total lines:", total_lines)
print("Subject lines:", subject_lines)
print("Percentage:", percent)

"""## Problem 8: File Statistics Summary

Write a program that:
1) Prompts for a filename (with `try/except`)
2) Reads line by line
3) Computes:
   - total lines
   - total characters (include spaces)
   - total words (split on whitespace)
   - average words per line (non-empty lines only)
4) Prints a neat summary.
"""

# Write your solution here

filename = input("Enter file name: ")

try:
    fl = open(filename)
except:
    print("File can't found")
    exit()

lines = 0
characters = 0

for line in fl:
    lines = lines + 1
    characters = characters +  len(line)

print("Total lines:", lines)
print("Total characters:", characters)