# -*- coding: utf-8 -*-
"""Assignment02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ow7Bp-VfbW9QOGSLndtriqps70GMOe8-

# Assignment 2

## Problem 1

Ask for a first name and last name (two inputs). Print them in the format: `Last, First`.
"""

# TODO: Read first name
# TODO: Read last name
# TODO: Print as: Last, First

first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
print(f"{last_name}, {first_name}")

"""## Problem 2

Ask the user for an integer. Convert it to int and print the next integer (n + 1).
"""

# TODO: Read input
# TODO: Convert to int
# TODO: Print n + 1

n = int(input("Any integer number: "))
print(n + 1)

"""## Problem 3

Ask the user for a decimal number. Convert to float and print it rounded to 2 decimal places.
"""

# TODO: Read input
# TODO: Convert to float
# TODO: Print rounded to 2 decimals (hint: round(x, 2))

n = float(input("Enter decimal Number: "))
print(round(n, 2))

"""## Problem 4

Given `text = '8'`, convert it to int, add 12, and print the result.
"""

text = '8'

# TODO: Convert text to int
# TODO: Add 12 and print

num = int(text)
print(num+12)

"""## Problem 5

Given `s = 'banana'`, print the largest character and the smallest character using `max()` and `min()`.
"""

s = 'banana'

# TODO: Print max(s)
# TODO: Print min(s)

print(max(s))
print(min(s))

"""## Problem 6

Write a function `show_banner()` that prints exactly three lines:
`**********`
`*  PYTHON *`
`**********`
Then call it twice.
"""

# TODO: Define show_banner()

# TODO: Call show_banner()
# TODO: Call show_banner() again

def show_banner():
    print("**********")
    print("* PYTHON *")
    print("**********")

show_banner()
show_banner()

"""## Problem 7

Write a function `repeat_word(word, times)` that prints `word` repeated `times` times on one line, separated by spaces. Test with `('hi', 3)`.
"""

# TODO: Define repeat_word(word, times)

# TODO: Call repeat_word('hi', 3)


def repeat_word(word, times):
    print((word + " ") * times)

repeat_word('hi', 5)

"""## Problem 8

Write a function `km_to_miles(km)` that returns miles (1 km = 0.621371 miles). Print the result for 5 km.
"""

# TODO: Define km_to_miles(km) to return miles

# TODO: Print km_to_miles(5)


def km_to_miles(km):
    return km * 0.621371

print(km_to_miles(5))
print(km_to_miles(7))

"""## Problem 9

Write a function `is_even(n)` that returns `True` if `n` is even, otherwise `False`. Print results for 10 and 7.
"""

# TODO: Define is_even(n)

# TODO: Print is_even(10)
# TODO: Print is_even(7)

def is_even(n):
  return n % 2 == 0

print(is_even(6))
print(is_even(9) )

"""## Problem 10

Write a function `clamp(x, low, high)` that returns:
- `low` if `x < low`
- `high` if `x > high`
- otherwise `x`
Print results for `clamp(5, 1, 10)`, `clamp(-2, 0, 3)`, `clamp(99, 0, 50)`.
"""

# TODO: Define clamp(x, low, high)

# TODO: Print clamp(5, 1, 10)
# TODO: Print clamp(-2, 0, 3)
# TODO: Print clamp(99, 0, 50)

def clamp(x, low, high):
    if x < low:
        print("low")
    elif x > high:
        print("high")
    else:
        print(x)

clamp(5, 1, 10)
clamp(-2, 0, 3)
clamp(99, 0, 50)

"""## Problem 11

Use a `while` loop to print all integers from 1 to 10 (inclusive).
"""

# TODO: Initialize a counter
# TODO: while loop to print 1..10

i = 1
while i<= 10:
    print(i)
    i = i+ 1

"""## Problem 12

Keep asking for a positive integer until the user enters one. Then print `OK` and the number.
"""

# TODO: Loop until a valid positive integer is entered
# TODO: Print OK and the number

while True:
    n = int(input("enter intiger: "))
    if n == 1:
        print("OK", n)
        break

"""## Problem 13

Read lines in a loop using `input('> ')`. Stop when the user enters an empty line `''` (just presses Enter). After stopping, print how many non-empty lines were entered.
"""

count = 0
# TODO: Loop, read line
# TODO: If line == '', break
# TODO: Otherwise increment count
# TODO: After loop, print count

while True:
    line = input("> ")
    if line == "":
        break
    count = count +  1
print("Non empty Lines = ", count)

"""## Problem 14

Read lines using `input('> ')`.
- If a line starts with `skip:`, ignore it using `continue`.
- If the line is `stop`, break.
- Otherwise print the line in uppercase.
"""

# TODO: while True loop
# TODO: Read line
# TODO: If startswith('skip:'), continue
# TODO: If line == 'stop', break
# TODO: Print line.upper()

while True:
    line = input("> ")
    if line == "skip:":
      continue
    if line == "stop":
      break
    print(line.upper())

"""## Problem 15

Repeatedly read integers until the user enters `done`.
Ignore any input that is not a valid integer (use `try/except` and `continue`).
At the end, print the total sum of valid integers.
"""

total = 0
# TODO: Loop and read input
# TODO: Break on 'done'
# TODO: Try converting to int; if fails, continue
# TODO: Add to total
# TODO: Print total

while True:
    val = input("enter: ")
    if val == "done":
        break
    try:
        total = total +  int(val)
    except:
        continue
print(total)

"""## Problem 16

Given `nums = [2, 5, 8, 11, 14]`, use a `for` loop to print each number squared on its own line.
"""

nums = [2, 5, 8, 11, 14]
# TODO: Loop and print each number squared
for n in nums:
    print(n * n)

"""## Problem 17

Given `words = ['cat', 'elephant', 'dog', 'ant']`, use a `for` loop to print each word and its length on one line (example: `cat 3`).
"""

words = ['cat', 'elephant', 'dog', 'ant']
# TODO: Loop and print word and len(word)

for word in words:
    print(word, len(word))

"""## Problem 18

Given `nums = [3, 7, 7, 1, 9, 7]`, count how many times 7 appears using a loop (do NOT use `count()`). Print the count.
"""

nums = [3, 7, 7, 1, 9, 7]
count = 0
# TODO: Loop and count 7s
# TODO: Print count

for n in nums:
    if n == 7:
        count = count + 1
print(count)

"""## Problem 19

Given `nums = [10, 20, 30, 40]`, compute the average using a loop. Print the average.
"""

nums = [10, 20, 30, 40]
total = 0
count = 0
# TODO: Loop to compute total and count
# TODO: Compute average and print

for n in nums:
    total = total + n
    count = count+ 1
print(total / count)

"""## Problem 20

Given `nums = [4, 17, 9, 22, 5, 30]`, print only the numbers that are multiples of 3.
"""

nums = [4, 17, 9, 22, 5, 30]
# TODO: Loop and print numbers divisible by 3


for n in nums:
    if n % 3 == 0:
        print(n)

"""## Problem 21

Given `nums = [6, 2, 9, 1, 5]`, find the largest number without using `max()`. Print it.
"""

nums = [6, 2, 9, 1, 5]
largest = None
# TODO: Loop and update largest
# TODO: Print largest

for n in nums:
    if largest is None or n > largest:
        largest = n
print(largest)

"""## Problem 22

Given `nums = [6, 2, 9, 1, 5]`, find the smallest number without using `min()`. Print it.
"""

nums = [6, 2, 9, 1, 5]
smallest = None
# TODO: Loop and update smallest
# TODO: Print smallest

for n in nums:
    if smallest is None or n < smallest:
        smallest = n
print(smallest)

"""## Problem 23

Given `nums = [1, 4, 6, 8, 10]` and `target = 6`, use a boolean variable `found` (start `False`) to check whether the target is in the list. Print `found`.
"""

nums = [1, 4, 6, 8, 10]
target = 6
found = False
# TODO: Loop and set found = True if target is found
# TODO: Print found

for n in nums:
    if n == target:
        found = True
        break
print(found)

"""## Problem 24

Write a function `count_vowels(s)` that returns how many vowels are in `s` (a, e, i, o, u). Print the result for `'education'`.
"""

# TODO: Define count_vowels(s)

# TODO: Print count_vowels('education')

def count_vowels(s):
    vowels = "aeiou"
    count = 0
    for ch in s:
        if ch in vowels:
            count = count + 1
    return count

print(count_vowels("education"))

"""## Problem 25

Write a function `summarize(nums)` that returns a tuple:
`(count, total, average, smallest, largest)`
Constraints: no `len()`, `sum()`, `min()`, `max()`.
Test with `data = [12, 3, 19, 7, 7, 25]` and print the returned tuple.
"""

# TODO: Define summarize(nums)
# TODO: Compute count, total, smallest, largest using loop idioms
# TODO: Compute average after loop
# TODO: Return (count, total, average, smallest, largest)

data = [12, 3, 19, 7, 7, 25]
# TODO: Print summarize(data)