# -*- coding: utf-8 -*-
"""Day_93.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrVtj1JCIBLqBpsvF6Inj_fPMRUKYwRr

# Chapter 6 — Strings

## String Data Type & Concatenation
"""

str1 = "Hello"
str2 = 'there'
bob = str1 + str2
print(bob)

str3 = '123'

# This will cause an error
# str3 = str3 + 1

x = int(str3) + 1
print(x)

"""## Reading and Converting Input"""

name = input('Enter: ')
print(name)

apple = input('Enter: ')
# x = apple - 10  # This would cause an error
x = int(apple) - 10
print(x)

"""## Looking Inside Strings"""

fruit = 'banana'
letter = fruit[1]
print(letter)

x = 3
w = fruit[x - 1]
print(w)

"""## 4️⃣ Index Error Example"""

zot = 'abc'
print(zot[5])  # Uncomment to see IndexError

"""## Length of a String (len)"""

fruit = 'banana'
print(len(fruit))

x = len(fruit)
print(x)

"""## Looping Through Strings (while loop)"""

fruit = 'banana'
index = 0
while index < len(fruit):
    letter = fruit[index]
    print(index, letter)
    index = index + 1

"""## Looping Through Strings (for loop)"""

fruit = 'banana'
for letter in fruit:
    print(letter)

"""## Looping and Counting"""

word = 'banana'
count = 0
for letter in word:
    if letter == 'a':
        count = count + 1
print(count)

"""## Slicing Strings"""

s = 'Monty Python'
print(s[0:4])
print(s[6:7])
print(s[6:20])

print(s[:2])
print(s[8:])
print(s[:])

"""##  String Concatenation"""

a = 'Hello'
b = a + 'There'
print(b)

c = a + ' ' + 'There'
print(c)

"""## Using 'in' as Logical Operator"""

fruit = 'banana'
print('n' in fruit)
print('m' in fruit)
print('nan' in fruit)

if 'a' in fruit:
    print('Found it!')

"""## String Comparison"""

word = input("Enter a word: ")

if word == 'banana':
    print('All right, bananas.')

if word < 'banana':
    print('Your word,' + word + ', comes before banana.')
elif word > 'banana':
    print('Your word,' + word + ', comes after banana.')
else:
    print('All right, bananas.')

"""## String Library Functions"""

greet = 'Hello Bob'
zap = greet.lower()
print(zap)
print(greet)
print('Hi There'.lower())

stuff = 'Hello world'
print(type(stuff))
print(dir(stuff))

"""## Searching a String (find)"""

fruit = 'banana'
pos = fruit.find('na')
print(pos)

aa = fruit.find('z')
print(aa)

"""## Upper & Lower Case"""

greet = 'Hello Bob'
nnn = greet.upper()
print(nnn)

www = greet.lower()
print(www)

"""## Search and Replace"""

greet = 'Hello Bob'
nstr = greet.replace('Bob','Jane')
print(nstr)

nstr = greet.replace('o','X')
print(nstr)

"""## Stripping Whitespace"""

greet = '   Hello Bob  '
print(greet.lstrip())
print(greet.rstrip())
print(greet.strip())

"""## Prefix Checking (startswith)"""

line = 'Please have a nice day'
print(line.startswith('Please'))
print(line.startswith('p'))