# -*- coding: utf-8 -*-
"""Assignment01 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRtERRl6yxacRuanJrhdDtGhxmALd3J1

# CSE 101: Assignment 01

This notebook contains **coding exercises** for the topics variables, expressions, types, input, conditionals.

**Instructions for students**
- Run each code cell after you finish it.
- Keep your solutions inside the provided cells.
- Save the notebook as pdf with all the outputs and upload it on Canvas

## Exercise 1: Variables

Task: Store your name, university, and favorite number in variables and print them in one line.
Output format: `Name: X | University: Y | Favorite: Z`
"""

# TODO: Write your solution here
name = "Hamim"
university = "NSU"
favourite = 95

print(f"Name: {name} | University: {university} | Favorite: {favourite}")

"""## Exercise 2: Swap Two Variables

Task: Ask for two numbers `a` and `b` and swap them.
- Print before and after.
- Use a third variable

"""

# TODO: Write your solution here
x = 10
y = 5
print("Before Swap ", x,y)

temp = x
x = y
y = temp

print("After Swap ", x,y)

"""## Exercise 3: Basic Calculator

Task: Input two integers and print:
- sum, difference, product, division, remainder, power (`**`)
Example output:
```
sum = ...
diff = ...
prod = ...
div = ...
mod = ...
pow = ...
```

"""

# TODO: Write your solution here

x = float(input("Enter First Number: "))
y = float(input("Enter Second Number: "))

print("Sum = ",x+y)
print("Diff = ",x-y)
print("Prod = ",x*y)
print("div = ",x/y)
print("Mod = ",x%y)
print("Pow = ",x**y)

"""## Exercise 4: Operator Precedence

Task: Read `a, b, c` (as integers) and compute:
1. `a + b * c`
2. `(a + b) * c`
3. `a ** b / c`
Print all three results clearly.

"""

# TODO: Write your solution here
a = 5
b = 6
c = 3

print("a+b*c = ",a+b*c)

print("(a+b)*c = ",(a+b)*c)

print("a ** b / c = ",a ** b / c)

"""## Exercise 5:

Task: Input total minutes (int). Convert to:
- hours = minutes // 60
- remaining = minutes % 60
Print: `X hour(s) Y minute(s)`

"""

# TODO: Write your solution here
minutes = int(input("Enter Minute: "))

hours = minutes // 60
remaining = minutes % 60

print(f"{hours} hour {remaining} minute")

"""## Exercise 6: Type Conversion

Task: Input a number as a string and:
- Convert to int
- Convert to float
- Print both and their types using `type()`

"""

# TODO: Write your solution here
string_num = "10"

int_num = int(string_num)
float_num = float(string_num)

print(f"Int Val: {int_num}")
print(f"Int Type: {type(int_num)}")

print(f"Float Value: {float_num}")
print(f"Float Type: {type(float_num)}")

"""## Exercise 7:

Task: Read Celsius (float) and print Fahrenheit using:
`F = (C * 9/5) + 32`

"""

# TODO: Write your solution here

celsius = float(input("Celsius: "))
fahrenheit = (celsius * 9/5) + 32

print(f"{celsius} celsius =  {fahrenheit} farenheit")

"""## Exercise 8:

Task: Input radius (float). Print:
- area = πr²
- circumference = 2πr  
Use `pi = 3.1416`

"""

# TODO: Write your solution here
pi = 3.1416
r = float(input("Enter radius: "))

area = pi * r * r
circumference = 2 * pi * r

print("Area =", area)
print("Circumference =", circumference)

"""## Exercise 9:

Task: Ask for hours and rate, compute gross pay.
- hours can be float
- rate can be float
Print: `Pay: <value>`

"""

# TODO: Write your solution here

hours = float(input("Enter hours: "))
rate = float(input("Enter Rate: "))

gross_pay = hours * rate

print("Pay:", gross_pay)

"""## Exercise 10:

Task:
- If hours > 40, extra hours are paid at **1.5× rate**
- Otherwise normal pay  
Print: `Pay: <value>`

"""

# TODO: Write your solution here

hours = float(input("Enter hours: "))
rate = float(input("Enter Rate: "))

if hours > 40:
    extra_time = hours - 40
    pay = (40 * rate) + (extra_time * rate * 1.5)
else:
    pay = hours * rate

print("Pay:", pay)

"""## Exercise 11:
Task: Input a mark (0–100). Print:
- A: 90–100
- B: 80–89
- C: 70–79
- D: 60–69
- F: <60  
Also handle invalid marks (<0 or >100): print `Invalid`

"""

# TODO: Write your solution here


mark = float(input("Enter Your Marks: "))

if mark < 0 or mark > 100:
    print("Invalid")
elif mark >= 90:
    print("A")
elif mark >= 80:
    print("B")
elif mark >= 70:
    print("C")
elif mark >= 60:
    print("D")
else:
    print("F")

"""## Exercise 12:

Task: Input integer `x`. Print:
- `Small` if x < 2  
- `Medium` if 2 ≤ x < 10  
- `Large` if x ≥ 10

"""

# TODO: Write your solution here

x = int(input("Enter any integer: "))

if x < 2:
    print("Small")
elif x == 2 or x < 10:
    print("Medium")
else:
    print("Large")

"""## Exercise 13: Compare Two Numbers

Task: Input `a` and `b`. Print:
- `a is greater`
- `b is greater`
- `equal`

"""

# TODO: Write your solution here

a = float(input("Enter a: "))
b = float(input("Enter b: "))

if a > b:
    print("a is greater")
elif b > a:
    print("b is greater")
else:
    print("equal")

"""## Exercise 14: Even / Odd Checker

Task: Input integer `n`. Print `Even` or `Odd` using `%`.

"""

# TODO: Write your solution here

n = int(input("Enter any number: "))

if n % 2 == 0:
    print("Even number")
else:
    print("Odd Number")

"""## Exercise 15: Safe Integer Input (try/except)

Task: Ask user for a number.
- If it’s a valid integer: print `Nice work`
- Otherwise: print `Not a number`

"""

# TODO: Write your solution here


try:
    n = int(input("Enter a number: "))
    print("Nice work")
except:
    print("Not a number")

"""## Exercise 16: Safe Pay Calculator

Task: Combine overtime + safe input:
- Ask for hours and rate
- If either is invalid: print `Error, please enter numeric input`
- Else compute overtime pay and print it

"""

# TODO: Write your solution here

try:
  hours = float(input("Enter hours: "))
  rate = float(input("Enter Rate: "))

  if hours > 40:
      extra = hours - 40
      pay = (40 * rate) + (extra * rate * 1.5)
  else:
      pay = hours * rate

  print("Pay:", pay)

except:
    print("Error, please enter numeric input")

"""## Exercise 17:

Task:
- Input a European floor (int)
- Convert to US floor = eu + 1
Print: `US floor: <value>`

"""

# TODO: Write your solution here

european_floor = int(input("Enter European floor: "))

us_floor = european_floor + 1

print("US floor:", us_floor)

"""## Exercise 18: Mini Receipt Program

Task: Input:
- item name (string)
- unit price (float)
- quantity (int)
Compute total and print a mini receipt.

"""

# TODO: Write your solution here

item = input("Item name: ")
price = float(input("Unit price: "))
quantity = int(input("Quantity: "))

total_price = price * quantity

print("\n---------- CASH MEMO----------")
print("Item Name :", item)
print("Unit Price :", price)
print("Quantity :", quantity)
print("Total Price :", total_price)
print("---------------------------------")

"""## Exercise 19: Commenting

Task: Write any small program (e.g., circle area) and:
- Add a comment on top with your name + today's date
- Add at least 3 inline comments explaining important lines

"""

# Name: Kazi Hamim Ahmed
# Date: 07/02/2026

# TODO: Write your solution here

pi = 3.1416 # define the value of pi which is 3.1416
r = float(input("Enter radius: ")) # Taking Input from user

area = pi * r * r # Calculate the area
circumference = 2 * pi * r # Calculate the circumference

print("Area =", area) # Print the area
print("Circumference =", circumference) # print the circumference

"""## Exercise 20:

Task: Make a program that:
1. Takes user name (string)
2. Takes hours + rate (numbers, safe input using try/except)
3. Computes overtime pay
4. Prints a clean payslip

"""

# TODO: Write your solution here

name = input("Enter your name: ")

try:
    hours = float(input("Enter Hours Work: "))
    rate = float(input("Enter Hourly Rate: "))

    if hours > 40:
        overtime_hours = hours - 40
        normal_pay = 40 * rate
        overtime_pay = overtime_hours * rate * 1.5
        total_pay = normal_pay + overtime_pay
    else:
        normal_pay = hours * rate
        overtime_pay = 0
        total_pay = normal_pay

    print("\n----------- PAYSLIP ----------")
    print("Name:", name)
    print("Hours Worked:", hours)
    print("Hourly Rate:", round(rate, 2))
    print("Normal Pay:", round(normal_pay, 2))
    print("Overtime Pay:", round(overtime_pay, 2))
    print("Total Pay:", round(total_pay, 2))
    print("---------------------------------")

except:
    print("Error: Please enter numeric input for hours and rate")