# -*- coding: utf-8 -*-
"""Assignmnent05-solve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbjAWZzLXQRWrNPkTx8CZUlp94Z2IH3-

# Assignment 5: Lists, Dictionaries, and Tuples

## **Problem 1**

Ask the user to enter numbers until they type `"done"`.

Store the numbers in a list.

After input ends, print:

- The full list
- The largest number
- The smallest number
- The sum of the numbers
- The average of the numbers
"""

# Write your solution here

nummbers = []

while True:
    x = input("Enter your number: ")
    if x == "done":
        break
    nummbers.append(int(x))

print("List:", nummbers)
print("Largest Number:", max(nummbers))
print("Smallest number:", min(nummbers))
print("Sum:", sum(nummbers))
print("Average:", sum(nummbers)/len(nummbers))

"""## **Problem 2**

Given the list:

`numbers = [8, 3, 15, 6, 2]`

Write a program that prints all elements greater than 5.
"""

# Write your solution here

numbers = [8, 3, 15, 6, 2]

for n in numbers:
    if n > 5:
        print(n)

"""## **Problem 3**

Given the list:

```python
values = [12, 5, 8, 21, 3, 18, 10, 7, 16]
```

Create three new lists:

- numbers **less than 10**
- **even numbers**
- **odd numbers**

Print all three lists.

### Example Output
```python
Less than 10: [5, 8, 3, 7]
Even numbers: [12, 8, 18, 10, 16]
Odd numbers: [5, 21, 3, 7]
```

"""

# Write your solution here

values = [12, 5, 8, 21, 3, 18, 10, 7, 16]
less_than_ten = []
even = []
odd = []


for v in values:
    if v < 10:
        less_than_ten.append(v)
    if v % 2 == 0:
        even.append(v)
    else:
        odd.append(v)



print("Less than ten:", less_than_ten)
print("Even numbers:", even)
print("Odd numbers:", odd)

"""## **Problem 4**

Given:

`values = [12, 7, 19, 3, 15, 8]`

Count how many numbers are even.
"""

# Write your solution here

values = [12, 7, 19, 3, 15, 8]
count = 0

for v in values:
  if v % 2 == 0:
    count = count + 1
print(count)

"""## **Problem 5**

Create two lists:

`a = [1,2,3]`

`b = [4,5,6]`

Combine them into a new list and print the result.
"""

# Write your solution here

a = [1,2,3]
b = [4,5,6]

new_list = a + b
print(new_list)

"""## **Problem 6**

Create a dictionary storing:

`{'Python':30, 'AI':25, 'Database':40}`

Print the number of students in the Python course.

Ask the user to enter a word.

Check whether it exists as a key in the above dictionary.
"""

# Write your solution here

courses = {'Python':30,'AI':25,'Database':40}

print("Python courses students :", courses['Python'])

word = input("Enter course name: ")

if word in courses:
    print("found")
else:
    print("Not found")

"""## **Problem 7**

Given:

`scores = {'Alice':85, 'Bob':90, 'Charlie':78}`

Use a loop to print all keys and values.
"""

# Write your solution here

scores = {'Alice':85, 'Bob':90, 'Charlie':78}

for key in scores:
  print(key, scores[key])

"""## **Problem 8**

Given the list:

```python
names = ['ana', 'bob', 'ana', 'carl', 'bob', 'ana', 'dina', 'carl', 'ana']
```

Create a dictionary that counts how many times each name appears.

Then print:

- the dictionary
- the name with the **highest count**
- its count

### Example Output
```python
{'ana': 4, 'bob': 2, 'carl': 2, 'dina': 1}
Most frequent name: ana
Count: 4
```
"""

# Write your solution here

names = ['ana', 'bob', 'ana', 'carl', 'bob', 'ana', 'dina', 'carl', 'ana']

count = {}

for n in names:
  count[n] = names.count(n)

heighest_name = max(count, key=count.get)

print(count)
print("Most frequent name:", heighest_name)
print("Count:", count[heighest_name])

"""## **Problem 9**

Given the following text:

```python
text = '''
Learning Python is fun and powerful
Python helps solve problems with simple code
Good programmers practice every day
Practice improves problem solving skills
Python makes programming enjoyable
'''
```

Write a program that:

1. Splits the text into individual words.
2. Creates a dictionary that counts how many times each word appears.
3. Print the dictionary
"""

# Write your solution here


text = '''
Learning Python is fun and powerful
Python helps solve problems with simple code
Good programmers practice every day
Practice improves problem solving skills
Python makes programming enjoyable
'''

words = text.split()
d = {}

for w in words:
    d[w] = words.count(w)

print(d)

"""## **Problem 10**

Given the dictionary:

```python
scores = {
    'Alice': 85,
    'Bob': 91,
    'Charlie': 78,
    'Diana': 91,
    'Evan': 88,
    'Farah': 78
}
```

Find the **highest score** and print the names of **all students** who have that score.

### Example Output
```text
Highest score: 91
Students:
Bob
Diana
```
"""

# Write your solution here
scores = {
    'Alice': 85,
    'Bob': 91,
    'Charlie': 78,
    'Diana': 91,
    'Evan': 88,
    'Farah': 78
}

heighes_score = max(scores.values())
print("heighest Score : ",heighes_score)

print("Students:")
for k,v in scores.items():
    if v == heighes_score:
        print(k)

"""## **Problem 11**

Create the tuple:

`colors = ('red','green','blue')`

1. Print all elements using a loop.
2. Print the length of the tuple
"""

# Write your solution here

colors = ('red','green','blue')

for c in colors:
  print(c)
print("Length of the tuple : ", len(colors))

"""**Problem 12**

Use tuple assignment:

`(x,y) = (5,10)`

Print the values of x and y.
"""

# Write your solution here

(x,y) = (5,10)

print(x)
print(y)

"""## **Problem 13**

Given the dictionary:

```python
prices = {
    'pen': 12,
    'book': 55,
    'bag': 320,
    'eraser': 8
}
```

Convert the dictionary into a list of tuples in the form:

```python
(value, key)
```

Sort the list in **reverse order** and print it.

### Example Output
```python
[(320, 'bag'), (55, 'book'), (12, 'pen'), (8, 'eraser')]
```
"""

# Write your solution here

prices = {
    'pen': 12,
    'book': 55,
    'bag': 320,
    'eraser': 8
}

lst = []

for k,v in prices.items():
    lst.append((v,k))

lst.sort(reverse=True)
print(lst)

"""## **Problem 14**

Given:

```python
pairs = [(2, 5), (1, 9), (2, 3), (1, 7), (3, 1)]
```

Print the tuples in **sorted order**.

### Example Output
```python
[(1, 7), (1, 9), (2, 3), (2, 5), (3, 1)]
```
"""

# Write your solution here

pairs = [(2, 5), (1, 9), (2, 3), (1, 7), (3, 1)]
pairs.sort()
print(pairs)

"""# **Problem 15**

Given the list:

```python
data = [
    ('pen', 10),
    ('book', 5),
    ('eraser', 8),
    ('bag', 2)
]
```

Use **tuple unpacking** in a loop to print each item in the form:

### Example Output
```text
pen -> 10
book -> 5
eraser -> 8
bag -> 2
```

"""

# Write your solution here


data = [
    ('pen', 10),
    ('book', 5),
    ('eraser', 8),
    ('bag', 2)
]


for k,v in data:
    print(k,"->",v)

"""# **Problem 16**

Given:

```python
scores = [
    ('Asha', 67),
    ('Borna', 91),
    ('Ritu', 84),
    ('Nafi', 91),
    ('Sami', 67),
    ('Lopa', 84)
]
```

Create a dictionary where:

- each **key** is a score
- each **value** is the number of students who got that score

Print the dictionary.

### Example Output
```python
{67: 2, 91: 2, 84: 2}
```
"""

# Write your solution here

scores = [
    ('Asha', 67),
    ('Borna', 91),
    ('Ritu', 84),
    ('Nafi', 91),
    ('Sami', 67),
    ('Lopa', 84)
]

d = {}

for name,score in scores:
  if score not in d:
    d[score] = 1
  else:
    d[score] += 1
print(d)