# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15L2rNbn88-j8OzuWecN3bH1TJ97plzQ7

# Practice Assignment — Chapter 6: Strings

**Instructions:** Solve each problem in the code cell below it.
Do not modify the problem description cells.
Write your solution where indicated.

## Problem 1 — String Concatenation
Take two strings as input and print them concatenated with a space in between.
"""

# Your code here
str1 = input("Enter a string")
str2 = input("Enter another string")

print(str1 + " " + str2)

"""## Problem 2 — String to Integer Conversion
Take a numeric string as input and print the number increased by 25.
"""

# Your code here
num_str = input("Enter a number:")

num_str = int(num_str)
print(num_str + 25)

"""## Problem 3 — Indexing
Given the string 'programming', print the 4th character (index-based).
"""

# Your code here

str = "programming"
print(str[3])

"""## Problem 4 — Length of String
Take a string as input and print its length.
"""

# Your code here
str1 = input("Enter a string")
print(len(str1))

"""## Problem 5 — Counting Characters
Take a string as input and count how many times the letter 'e' appears.
"""

# Your code here
str1 = input("Enter a string ")
count = 0
for letter in str1:
    if letter == 'e':
        count = count + 1
print(count)

"""## Problem 6 — Slicing
Given the string 'Data Science', print only the word 'Science' using slicing.
"""

# Your code here
str = "Data Science"

slice = str[5:]
print(slice)

"""## Problem 7 — Using 'in'
Take a string as input and check whether the substring 'py' exists in it. Print True or False.
"""

# Your code here

str1 = input("Enter a string ")
print("py" in str1)

"""## Problem 8 — String Comparison
Take a word as input and compare it with the word 'apple'.
Print whether it comes before, after, or is equal to 'apple'.
"""

# Your code here
str1 = input("Enter a string ")

if str1 == 'apple':
    print('Equal to apple')

elif str1 < 'apple':
   print("before apple")

else:
    print("After apple")

"""## Problem 9 — Search and Replace
Take a sentence as input and replace all spaces with underscores ('_').
"""

# Your code here

str1 = input("Enter a string ")
nstr = str1.replace(" ",'_')
print(nstr)

"""## Problem 10 — Strip and Case Conversion
Take a string with extra spaces at the beginning and end.
Remove the spaces and convert the string to uppercase.
"""

# Your code here
str1 = input("Enter a string ")

print(str1.strip().upper())